"""Potential-based ordered goal graph shared by SIMPLE task families."""

from __future__ import annotations

import numpy as np

from simple.grasp_rl.rewards import RewardTerms
from simple.grasp_rl.state_v2 import MujocoTaskStateExtractor, TaskStateV2
from simple.grasp_rl.task_spec import GoalStageSpec, TaskSpecV2


class GoalGraphReward:
    """Evaluate declarative stages without a task-specific reward class."""

    # Stage history is part of the augmented Markov state.  With long
    # 800--1200 step motions, gamma<1 inside the shaping term charges a
    # negative reward for every unchanged valid hold.  Use the undiscounted
    # potential difference; PPO still applies its own return discount.
    gamma = 1.0

    def __init__(
        self,
        extractor: MujocoTaskStateExtractor,
        spec: TaskSpecV2,
        max_episode_steps: int | None = None,
        profile: str = "grail_release_v1",
    ):
        self.extractor = extractor
        self.spec = spec
        self.max_episode_steps = (
            spec.max_episode_steps
            if max_episode_steps is None
            else max_episode_steps
        )
        self.profile = profile
        self.reset()

    def reset(self) -> None:
        self.step_count = 0
        self.stage_index = 0
        self.stage_hold = 0
        self.previous_potential = 0.0
        self.fall_count = 0
        self.danger_count = 0
        self.drop_count = 0
        self.ever_lifted = False
        self.initial_transport_distance: float | None = None
        self.reference_should_contact: float | None = None
        self.reference_contact_center_primary: np.ndarray | None = None
        self.extractor.set_stage(0, 0.0)

    def set_reference_contact(
        self,
        should_contact: float | None,
        contact_center_primary: np.ndarray | None = None,
    ) -> None:
        """Set GRAIL's per-frame contact intent and reference contact centre.

        GRAIL uses a contact point stored by the reference motion, not a point
        generated by the policy's current collision.  Store the point in the
        primary object's local frame so target-pose randomization remains valid.
        Older prepared SIMPLE data has no contact-centre field and therefore
        deliberately falls back to the current object centre, matching GRAIL's
        own missing-contact-centre fallback.
        """

        self.reference_should_contact = (
            None if should_contact is None else float(bool(should_contact))
        )
        self.reference_contact_center_primary = (
            None
            if contact_center_primary is None
            else np.asarray(contact_center_primary, dtype=np.float64).copy()
        )

    @staticmethod
    def _hand_grasp(state: TaskStateV2, hand: str) -> tuple[bool, float]:
        index = 0 if hand == "left" else 1
        magnitudes = np.linalg.norm(state.contact_forces_pelvis[index], axis=-1)
        thumb = float(magnitudes[1:4].max(initial=0.0))
        support = float(magnitudes[4:8].max(initial=0.0))
        quality = float(np.clip(min(thumb, support) / 8.0, 0.0, 1.0))
        contact = state.left_primary_contact if hand == "left" else state.right_primary_contact
        return bool(contact and thumb > 2.0 and support > 2.0), quality

    def _grail_grasp_terms(
        self, state: TaskStateV2, hand: str = "right"
    ) -> tuple[float, float]:
        """Released GRAIL contact-count and finger-opposition rewards."""

        hand_index = 0 if hand == "left" else 1
        magnitudes = np.linalg.norm(
            state.contact_forces_pelvis[hand_index], axis=-1
        )
        # GRAIL pnp_table uses all eight configured hand links, a 0.1 N
        # threshold, and min_contacts=8.
        contact_fraction = float(np.clip(np.sum(magnitudes > 0.1) / 8.0, 0.0, 1.0))
        actual_contact = (
            state.left_primary_contact if hand == "left" else state.right_primary_contact
        )
        contact_intent = (
            float(actual_contact)
            if self.reference_should_contact is None
            else self.reference_should_contact
        )

        center = state.primary.pos_w
        if self.reference_contact_center_primary is not None:
            center = (
                state.primary.pos_w
                + state.primary.rot_w @ self.reference_contact_center_primary
            )
        vectors = state.distal_pos_w[hand_index] - center[None, :]
        vectors /= np.linalg.norm(vectors, axis=-1, keepdims=True).clip(1e-6)
        support = vectors[1:].mean(axis=0)
        support /= max(float(np.linalg.norm(support)), 1e-6)
        opposition = float(-np.dot(vectors[0], support))
        return contact_fraction * contact_intent, opposition * contact_intent

    def _articulation_progress(self, state: TaskStateV2) -> tuple[float, bool]:
        goal = self.spec.articulation
        if goal is None or not state.articulation_raw:
            return 0.0, False
        values = state.articulation_raw
        pairs = list(zip(values, goal.targets, strict=False))
        if goal.comparison == "ge":
            progress = min(np.clip(q / max(abs(t), 1e-3), 0.0, 1.0) for q, t in pairs)
            complete = all(q >= t for q, t in pairs)
        elif goal.comparison == "le":
            progress = min(np.clip(q / min(t, -1e-3), 0.0, 1.0) for q, t in pairs)
            complete = all(q <= t for q, t in pairs)
        elif goal.comparison == "abs_ge":
            progress = max(np.clip(abs(q) / max(abs(t), 1e-3), 0.0, 1.0) for q, t in pairs)
            complete = any(abs(q) >= abs(t) for q, t in pairs)
        else:  # any_ge
            progress = max(np.clip(q / max(abs(t), 1e-3), 0.0, 1.0) for q, t in pairs)
            complete = any(q >= t for q, t in pairs)
        return float(progress), bool(complete)

    def _stage(self, stage: GoalStageSpec, state: TaskStateV2) -> tuple[float, bool, dict[str, float]]:
        left_grasp, left_quality = self._hand_grasp(state, "left")
        right_grasp, right_quality = self._hand_grasp(state, "right")
        primary = state.primary
        destination = state.destination
        auxiliary = state.auxiliary
        distance = float(np.min(state.fingertip_distances))
        lift = float(primary.pos_w[2] - state.initial_primary_pos[2]) if primary.present else 0.0
        xy = float(np.linalg.norm(primary.pos_w[:2] - destination.pos_w[:2])) \
            if primary.present and destination.present else np.inf
        aux_xy = float(np.linalg.norm(auxiliary.pos_w[:2] - destination.pos_w[:2])) \
            if auxiliary.present and destination.present else np.inf
        primary_aux_xy = float(np.linalg.norm(primary.pos_w[:2] - auxiliary.pos_w[:2])) \
            if primary.present and auxiliary.present else np.inf
        stable = bool(primary.present and np.linalg.norm(primary.lin_vel_w) < self.spec.stable_linear_speed
                      and np.linalg.norm(primary.ang_vel_w) < self.spec.stable_angular_speed)
        aux_stable = bool(auxiliary.present and np.linalg.norm(auxiliary.lin_vel_w) < self.spec.stable_linear_speed
                          and np.linalg.norm(auxiliary.ang_vel_w) < self.spec.stable_angular_speed)
        details = {"lift": lift, "xy": xy, "left_quality": left_quality,
                   "right_quality": right_quality, "stable": float(stable)}

        if stage.primitive == "approach":
            progress = float(np.exp(-20.0 * max(distance, 0.0)))
            return progress, distance <= stage.threshold, details
        if stage.primitive == "contact":
            active = state.left_primary_contact if stage.hand == "left" else state.right_primary_contact
            if stage.hand == "both":
                active = state.left_primary_contact and state.right_primary_contact
            return float(active), bool(active), details
        if stage.primitive == "grasp":
            active, quality = (left_grasp, left_quality) if stage.hand == "left" else (right_grasp, right_quality)
            return quality, active, details
        if stage.primitive == "bimanual":
            active = state.left_primary_contact and state.right_primary_contact
            return min(left_quality, right_quality), bool(active), details
        if stage.primitive == "handover":
            active = left_grasp and not state.right_primary_contact
            return float(active), bool(active), details
        if stage.primitive == "lift":
            progress = float(np.clip(lift / max(stage.threshold, 1e-3), 0.0, 1.0))
            # Entering this ordered stage already proves a force-verified
            # grasp.  Use the task's native object-lift predicate for terminal
            # success: requiring the instantaneous contact-force classifier to
            # remain true rejects demonstrably lifted objects when fingertips
            # transition from impact to a static hold.
            return progress, bool(lift >= stage.threshold), details
        if stage.primitive == "transport":
            if self.initial_transport_distance is None and np.isfinite(xy):
                self.initial_transport_distance = max(xy, stage.threshold + 1e-3)
            start = self.initial_transport_distance or 1.0
            progress = float(np.clip((start - xy) / max(start - stage.threshold, 1e-3), 0.0, 1.0))
            return progress * float(right_grasp or left_grasp), bool(xy <= stage.threshold and (right_grasp or left_grasp)), details
        if stage.primitive == "place":
            progress = float(np.exp(-8.0 * max(xy - stage.threshold, 0.0))) if np.isfinite(xy) else 0.0
            complete = xy <= stage.threshold and state.primary_destination_contact
            return progress, bool(complete), details
        if stage.primitive == "release_settle":
            no_hand = not state.left_primary_contact and not state.right_primary_contact
            complete = no_hand and state.primary_destination_contact and stable and xy <= self.spec.placement_xy_tolerance
            return float(complete), bool(complete), details
        if stage.primitive == "articulation":
            progress, complete = self._articulation_progress(state)
            return progress, complete, details
        if stage.primitive == "push":
            if not primary.present or not destination.present:
                return 0.0, False, details
            direction = destination.pos_w[:2] - state.initial_primary_pos[:2]
            norm = float(np.linalg.norm(direction))
            if norm < 1e-6:
                direction = np.array([1.0, 0.0])
            else:
                direction /= norm
            delta = primary.pos_w[:2] - state.initial_primary_pos[:2]
            projected = float(delta @ direction)
            lateral = float(abs(delta[0] * direction[1] - delta[1] * direction[0]))
            progress = float(np.clip(projected / max(stage.threshold, 1e-3), 0.0, 1.0))
            return progress, bool(projected >= stage.threshold and lateral <= .30), details
        if stage.primitive == "place_aux":
            complete = state.predicates[5] and primary_aux_xy <= self.spec.placement_xy_tolerance
            return float(np.exp(-8.0 * max(primary_aux_xy - self.spec.placement_xy_tolerance, 0.0))), bool(complete), details
        if stage.primitive == "aux_bimanual":
            complete = bool(state.predicates[2] and state.predicates[3])
            return float(complete), complete, details
        if stage.primitive == "aux_transport":
            progress = float(np.exp(-4.0 * max(aux_xy - stage.threshold, 0.0))) if np.isfinite(aux_xy) else 0.0
            complete = aux_xy <= stage.threshold and state.predicates[2] and state.predicates[3]
            return progress, bool(complete), details
        if stage.primitive == "aux_place":
            complete = aux_xy <= stage.threshold and bool(state.predicates[6])
            return float(np.exp(-8.0 * max(aux_xy - stage.threshold, 0.0))), bool(complete), details
        if stage.primitive == "aux_release_settle":
            no_hand = not state.predicates[2] and not state.predicates[3]
            complete = no_hand and bool(state.predicates[6]) and aux_stable
            return float(complete), bool(complete), details
        raise ValueError(f"Unknown goal primitive {stage.primitive!r}")

    def _advance_stage(self, completed: bool) -> tuple[bool, bool]:
        """Advance an ordered goal without completing the newly entered stage."""

        active_was_final = self.stage_index == len(self.spec.stages) - 1
        new_stage = bool(completed)
        success = bool(active_was_final and completed)
        if completed and not active_was_final:
            self.stage_index += 1
            self.stage_hold = 0
        return new_stage, success

    def compute(self, state: TaskStateV2, action: np.ndarray, previous_action: np.ndarray,
                action_range: np.ndarray) -> RewardTerms:
        self.step_count += 1
        stage = self.spec.stages[min(self.stage_index, len(self.spec.stages) - 1)]
        progress, predicate, details = self._stage(stage, state)
        self.stage_hold = self.stage_hold + 1 if predicate else 0
        completed = self.stage_hold >= stage.hold_steps
        new_stage, success = self._advance_stage(completed)
        if completed and not success:
            progress = 0.0
        potential = float(self.stage_index + np.clip(progress, 0.0, 1.0))
        graph_target = (
            5.0 * (self.gamma * potential - self.previous_potential)
            + 2.0 * float(new_stage)
        )
        self.previous_potential = potential

        final_stage = self.stage_index == len(self.spec.stages) - 1
        lift_height = float(details["lift"])
        self.ever_lifted |= lift_height >= min(self.spec.lift_height, .05)
        self.fall_count = self.fall_count + 1 if state.pelvis_height < .50 else 0
        dangerous_contact = bool(
            state.predicates[7]
            and self.spec.family in ("articulation", "push")
            and not final_stage
        )
        self.danger_count = self.danger_count + 1 if dangerous_contact else 0
        # A valid placement briefly has neither hand nor support contact while
        # the object settles onto the destination.  Treat a release as a drop
        # only when it stays low *and* remains clearly outside the goal region.
        # This preserves a real failure signal for release-after-lift while
        # avoiding a false terminal one or two simulation frames before table
        # contact is established.
        dropped_now = bool(
            self.ever_lifted
            and not state.left_primary_contact
            and not state.right_primary_contact
            and not state.primary_destination_contact
            and lift_height < .01
            and details["xy"] > 1.5 * self.spec.placement_xy_tolerance
        )
        self.drop_count = self.drop_count + 1 if dropped_now else 0
        failure = bool(
            self.fall_count >= 3 or self.danger_count >= 3 or self.drop_count >= 5
        )
        timeout = bool(self.step_count >= self.max_episode_steps and not (success or failure))
        use_grail = self.profile == "grail_release_v1" and self.spec.family == "grasp"
        terminal = (
            20.0
            if success
            else -10.0
            if failure
            else 0.0
            if use_grail and timeout
            else -5.0
            if timeout
            else 0.0
        )
        normalized_delta = (
            np.asarray(action) - np.asarray(previous_action)
        ) / np.maximum(action_range, 1e-3)
        raw_action_rate = float(np.mean(normalized_delta**2))
        action_rate = .002 * raw_action_rate
        forbidden = .5 if dangerous_contact else 0.0
        joint_limit = 0.0
        for name in self.extractor.robot.joint_names:
            model_joint = self.extractor.model.joint(name)
            if self.extractor.model.jnt_limited[model_joint.id]:
                q = float(self.extractor.data.joint(name).qpos[0])
                low, high = self.extractor.model.jnt_range[model_joint.id]
                margin = .03 * max(float(high - low), 1e-3)
                joint_limit += .01 * float(q < low + margin or q > high - margin)
        grail_grasp, grail_finger = self._grail_grasp_terms(state)
        if use_grail:
            # Directly mirror released pnp_table ratios. Robot-motion tracking
            # is added separately by ReferenceTracker with the corresponding
            # 2.5 anchor / 5.0 relative-body weighting.
            target_reward = 5.0 * grail_grasp + 10.0 * grail_finger
            wrist_distance = float(
                np.linalg.norm(state.hands[1].pos_w - state.primary.pos_w)
            )
            approach = float(
                np.sum(state.hands[1].lin_vel_w**2)
                * np.exp(-(wrist_distance**2) / (0.25**2))
            )
            table = float(state.predicates[7])
            penalty = 15.0 * approach + table + 0.1 * raw_action_rate
        else:
            target_reward = graph_target
            approach = 0.0
            table = forbidden
            penalty = .001 + action_rate + forbidden + joint_limit
        self.extractor.set_stage(self.stage_index, progress)
        is_grasp = self._hand_grasp(state, "left")[0] or self._hand_grasp(state, "right")[0]
        grasp_quality = max(float(details["left_quality"]), float(details["right_quality"]))
        stable = float(details["stable"])
        return RewardTerms(
            reach=float(np.exp(-20.0 * max(float(np.min(state.fingertip_distances)), 0.0))),
            pregrasp=progress if stage.primitive == "approach" else 0.0,
            contact=float(state.left_primary_contact or state.right_primary_contact),
            grasp_quality=grasp_quality, finger=grasp_quality,
            xy=float(np.exp(-max(float(details["xy"]) if np.isfinite(details["xy"]) else 10.0, 0.0))),
            lift=float(np.clip(lift_height / max(self.spec.lift_height, 1e-3), 0.0, 1.0)),
            stable=stable, hold=float(self.stage_hold), progress=potential,
            progress_bonus=2.0 * float(new_stage), grail_grasp=grail_grasp,
            grail_finger_direction=grail_finger, approach_penalty=approach,
            table_penalty=table, action_rate_penalty=raw_action_rate,
            joint_limit_penalty=joint_limit, target_reward=target_reward,
            penalty=penalty, terminal_adjustment=terminal, success=success,
            native_success=success, failure=failure, timeout=timeout,
            lift_height=lift_height, is_grasp=bool(is_grasp),
            hand_table_force=float(state.predicates[7]), stage_index=self.stage_index,
            stage_progress=float(progress), stage_name=stage.name,
        )
